services:
  banco-de-dados:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: votacao
      POSTGRES_USER: votacao
      POSTGRES_PASSWORD: votacao
    ports:
      - "5432:5432"
    volumes:
      - dados_postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U votacao -d votacao"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      URL_BANCO: jdbc:postgresql://banco-de-dados:5432/votacao
      USUARIO_BANCO: votacao
      SENHA_BANCO: votacao
    ports:
      - "8080:8080"
    depends_on:
      banco-de-dados:
        condition: service_healthy

volumes:
  dados_postgresql: