CREATE TABLE pauta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    descricao VARCHAR(1000) NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessao_votacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL,
    data_inicio TIMESTAMP WITH TIME ZONE NOT NULL,
    data_fim TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_sessao_votacao_pauta
        FOREIGN KEY (pauta_id) REFERENCES pauta (id),
    CONSTRAINT uk_sessao_votacao_pauta UNIQUE (pauta_id),
    CONSTRAINT ck_sessao_votacao_periodo CHECK (data_fim > data_inicio)
);

CREATE TABLE voto (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pauta_id BIGINT NOT NULL,
    cpf_associado VARCHAR(11) NOT NULL,
    escolha VARCHAR(3) NOT NULL,
    data_criacao TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_voto_pauta
        FOREIGN KEY (pauta_id) REFERENCES pauta (id),
    CONSTRAINT uk_voto_pauta_cpf_associado UNIQUE (pauta_id, cpf_associado),
    CONSTRAINT ck_voto_cpf_associado CHECK (cpf_associado ~ '^[0-9]{11}$'),
    CONSTRAINT ck_voto_escolha CHECK (escolha IN ('SIM', 'NAO'))
);

CREATE INDEX idx_voto_pauta_escolha ON voto (pauta_id, escolha);